AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false


inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Max: 35
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'xdescribe', 'xcontext', 'fdescribe', 'fcontext']
